### ISSUE TITLE
Chapter 11: Cat Adoption (Censoring and Survival) Code

### ISSUE THREAD

**Issue by balkinishu** [rmcelreath/statrethinking_winter2019#11]
Is it possible to get the code for the censored cat adoption example visualizations on Slide 51 and 53 of Lecture 12. 

I am still trying to grok through the material on survival models in Chapter 11, but it seems like there are some missing sections in the text related to the above two graphs that are making that harder. Thank you

**Comment by rmcelreath** [comment]
That section is definitely not finished.

I think the plots you mention are just the three different probabilities defined in that section.
```
l <- 0.1
# density
curve( dexp(x,l) , from=0, to=30 , ylim=c(0,0.1) , xlab="day" , ylab="Density" )
mtext( "Probability adopted on day x" )

# cumulative density
curve( 1 - exp(-l*x) , from=0, to=30 , ylim=c(0,1) , xlab="day" , ylab="probability" )
mtext( "Probability adopted by day x" )

# complementary cumulative density
curve( exp(-l*x) , from=0, to=30 , ylim=c(0,1) , xlab="day" , ylab="probability" )
mtext( "Probability not adopted by day x" )
```

**Comment by balkinishu** [comment]
Thank you professor McElreath. Much appreciated. You are an amazing writer. With bated breadth, I look forward to your revised chapters.
