### ISSUE TITLE
Chapter 11: Survival Models Log_lik = True error message

### ISSUE THREAD

**Issue by balkinishu** [rmcelreath/statrethinking_winter2019#19]
I am guessing that Log_lik=True isn't implemented for models like 

```
m11.14 <- ulam(
    alist(
        days_to_event|adopted==1 ~ exponential( lambda ),
        days_to_event|adopted==0 ~ custom(exponential_lccdf( !Y | lambda )),
        lambda <- 1.0/mu,
        log(mu) <- a[color_id],
        a[color_id] ~ normal(0,1)
    ), data=dat ,   log_lik=TRUE)
```

If i want to compare different survival models, is there some other method I can try? Could I code and compare with map2stan as an alternative?

Here's the first few lines of the error message:
Warning message in validityMethod(object):
"The following variables have undefined values:  log_lik[1],The following variables have undefined values:  log_lik[2],The following variables have undefined values:  log_lik[4],The following variables have undefined values:  log_lik[5],The following variables have undefined values:  log_lik[10],The following variables have undefined values:  log_lik[13],The following

**Comment by rmcelreath** [comment]
ulam isn't yet feature complete. Until it is, I suggest coding in Stan directly. map2stan will not handle these models, and I've stopped developing it further.

**Comment by balkinishu** [comment]
if possible, could you suggest some code samples I can study for implementing WAIC for multi-level survival models in stan?

**Comment by eveskew** [comment]
@balkinishu, if you're not already aware, the following software and underlying code base may be helpful. Not sure if it directly addresses implementation of WAIC though.
https://jburos.github.io/survivalstan/
https://github.com/hammerlab/survivalstan
