### ISSUE TITLE
Non-centered parameterization of multinormal

### ISSUE THREAD

**Issue by zhengchencai** [rmcelreath/statrethinking_winter2019#39]
Hi there,

I was trying to reparameterize the multinormal between intercept and slope in homework 9 because there are some divergent transitions

c(a,b)[did] ~ multi_normal( c(abar,bbar) , Rho , Sigma ),

It seems that there was a function "dmvnormNC" for this purpose, but I guess it's not in the current version. Could you please give some hint for this reparameterization? I've look Stan user guild there is an example of non-centered parameterization of multinormal but I'm not familiar with the way Stan model. I'm still relying on the rethinking package. 

Thanks,
Zhengchen

**Comment by rmcelreath** [comment]
There is a large section in Chapter 14 that details how to do this. Also there are examples in the README: https://github.com/rmcelreath/rethinking#multilevel-model-formulas
