### ISSUE TITLE
Week 5 Homework solutions - Stan issue?

### ISSUE THREAD

**Issue by vanagpau** [rmcelreath/statrethinking_winter2019#40]
I was having problems with Week 5 homework, so copied and ran the solution code below.

library(rethinking)
data(Wines2012)
d <- Wines2012
dat_list <- list(
S = standardize(d$score),
jid = as.integer(d$judge),
wid = as.integer(d$wine),
)
m1 <- ulam(
alist(
S ~ dnorm( mu , sigma ),
mu <- a[jid] + w[wid],
a[jid] ~ dnorm(0,0.5),
w[wid] ~ dnorm(0,0.5),
sigma ~ dexp(1)
), data=dat_list , chains=4 , cores=4 )

It doesn't run, but gives error:
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\BEN10~1\AppData\Local\Temp\RtmpS6E4Od\file21501e8230c6.stan', reason 'No such file or directory'
2: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file2150154a1615.cpp 2> file2150154a1615.cpp.err.txt' had status 1
3: In file(con, "r") :
  cannot open file 'file2150154a1615.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

Seems to be a common problem? https://github.com/stan-dev/rstan/issues/818

**Comment by rmcelreath** [comment]
data(wines2012), not data(Wines2012). I wonder if the lower case 'w' is something that happened in a recent push.

**Comment by vanagpau** [comment]
library(rethinking)
> data(wines2012)
Warning message:
In data(wines2012) : data set ‘wines2012’ not found
> d <- wines2012
Error: object 'wines2012' not found

**Comment by rmcelreath** [comment]
Then use the previous code, but remove the errant comma from the dat list? The code runs for me.

**Comment by vanagpau** [comment]
dat_list <- list(S = standardize(d$score),
jid = as.integer(d$judge),
wid = as.integer(d$wine))

m1 <- ulam(
alist(
S ~ dnorm( mu , sigma ),
mu <- a[jid] + w[wid],
a[jid] ~ dnorm(0,0.5),
w[wid] ~ dnorm(0,0.5),
sigma ~ dexp(1)
), data=dat_list , chains=4 , cores=4)

produces,

The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\BEN10~1\AppData\Local\Temp\RtmpS6E4Od\file21504f9e6cf2.stan', reason 'No such file or directory'
2: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file2150102d7cbc.cpp 2> file2150102d7cbc.cpp.err.txt' had status 1
3: In file(con, "r") :
  cannot open file 'file2150102d7cbc.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

**Comment by rmcelreath** [comment]
This has nothing to do with my code. It is Stan issue.
