### ISSUE TITLE
extract.prior() seems to be sampling posterior distribution

### ISSUE THREAD

**Issue by T-Engel** [rmcelreath/statrethinking_winter2019#6]
Hi @rmcelreath,

As I was doing this week's homework, I came across a problem with the extract.prior() function. I have the suspicion that it samples the posterior distribution instead of extracting priors.  I am using the most up-to-date version of rethinking from the experimental branch.

This is the model that I built:

```{r}
set.seed(777)
library(rethinking)
library(tidyverse)
data("Wines2012")


Wines2012$score= scale(Wines2012$score)
Wines2012<- Wines2012 %>% mutate(jid= as.integer(judge),
                     wid= as.integer(wine))
slim_dat<-Wines2012 %>% select(score, wid, jid) %>% as.list()

mod1<- ulam(
    alist(
    score ~ dnorm(mu, sigma),
    mu <- aj[jid] + aw[wid],
    aj[jid] ~ dnorm(0,0.5),
    aw[wid] ~ dnorm(0,0.5),
    sigma ~dexp(1)
    ), data = slim_dat, cores = 3)


precis(mod1, depth = 2)

```

Then I extracted the priors for prior predictive simulation and plotted them (the intercept for every judge in this case):

```{r}
priors<- extract.prior(mod1)

priors$aj %>% as.data.frame() %>% gather(key="judge", value= "prior") %>% ggplot(aes(x=judge, y= prior))+ geom_boxplot()
```

![image](https://user-images.githubusercontent.com/37897372/52067691-6fe51500-257b-11e9-832d-ee59be831c34.png)

I was expecting to see no differences between the judges- the model hasn't seen the data yet. Instead, the output looks pretty much like the posterior distribution in the precis-output:
       
.......... mean   sd  5.5% 94.5% n_eff Rhat
aj[1]  -0.28 0.20 -0.59  0.04   599 1.01
aj[2]   0.21 0.19 -0.10  0.50   576 1.00
aj[3]   0.21 0.20 -0.11  0.52   482 1.01
aj[4]  -0.55 0.20 -0.86 -0.22   518 1.00
aj[5]   0.79 0.19  0.48  1.09   501 1.00
aj[6]   0.47 0.19  0.18  0.78   613 1.00
aj[7]   0.13 0.19 -0.16  0.42   553 1.00
aj[8]  -0.66 0.20 -0.95 -0.33   671 1.00
aj[9]  -0.35 0.19 -0.66 -0.04   581 1.00
aw[1]   0.12 0.27 -0.28  0.56   824 1.00
aw[2]   0.09 0.27 -0.37  0.53   714 1.00
aw[3]   0.24 0.23 -0.15  0.60   878 1.00
aw[4]   0.48 0.25  0.08  0.89   577 1.00
aw[5]  -0.11 0.24 -0.50  0.26   786 1.00
aw[6]  -0.31 0.26 -0.71  0.10   793 1.00
aw[7]   0.25 0.26 -0.16  0.68  1294 1.00
aw[8]   0.23 0.26 -0.19  0.63   673 1.00
aw[9]   0.07 0.26 -0.37  0.49   865 1.01
aw[10]  0.11 0.27 -0.29  0.57   756 1.00
aw[11]  0.00 0.25 -0.40  0.40   892 1.00
aw[12] -0.02 0.27 -0.45  0.40   769 1.00
aw[13] -0.09 0.26 -0.50  0.35   939 1.00
aw[14]  0.00 0.26 -0.41  0.42   814 1.00
aw[15] -0.18 0.26 -0.56  0.24   974 1.00
aw[16] -0.16 0.27 -0.59  0.26   626 1.00
aw[17] -0.12 0.24 -0.49  0.26   757 1.00
aw[18] -0.72 0.26 -1.12 -0.34   597 1.00
aw[19] -0.14 0.25 -0.53  0.26   567 1.00
aw[20]  0.32 0.25 -0.08  0.70   672 1.00
sigma   0.85 0.05  0.78  0.93   877 1.00
`
 
And then I extracted samples from the posterior and produced the same plot:      
```{r}
posterior<- extract.samples(mod1)

posterior$aj %>% as.data.frame() %>% gather(key="judge", value= "parameter") %>% ggplot(aes(x=judge, y= parameter))+ geom_boxplot()
```
![image](https://user-images.githubusercontent.com/37897372/52067731-84c1a880-257b-11e9-9e9b-4c5b3beb2df0.png)

This is essentially the same graph that I got for the priors. Do you know why that is?

Shouldn't the priors look more like this:

```{r}
priors<-list(aj=matrix(rnorm(9*500,0,0.5), 500, 9),
             aw=matrix(rnorm(20*500,0,0.5), 500, 20),
             sigma =rexp(500,1))



priors$aj %>% as.data.frame() %>% gather(key="judge", value= "prior") %>% ggplot(aes(x=judge, y= prior))+ geom_boxplot()
```
![image](https://user-images.githubusercontent.com/37897372/52068256-99eb0700-257c-11e9-90ea-743c3c2df0ae.png)

I hope this makes any sense to you. Let me know what you think, please.

See you tomorrow!

**Comment by rmcelreath** [comment]
I have not yet written an extract.prior method for ulam. Just simulate on your own for now.
