### ISSUE TITLE
Chapter 11 

### ISSUE THREAD

**Issue by bingson** [rmcelreath/statrethinking_winter2019#7]
m11.14 from Statistical Rethinking Winter 2019 Lecture 13 doesn't appear in draft chapter 11 for the second edition downloaded from https://xcelab.net/rm/sr2/ (updated 20 Jan 2019).

There's a similar but different model at the end of draft chapter 11 (## R code 11.64 for model M00). 

Anyhow, I am looking for more information on survival models to better understand the cat adoption problem and figure out why I get an error message when I try to run m11.14.

When I run the below code in windows I get the following error message. Can somebody help me?

```
library(rethinking)
data(AustinCats)
d <- AustinCats

d$adopt <- ifelse( d$out_event=="Adoption" , 1 , 0 )
d$black <- ifelse( d$color=="Black" , 1 , 0 )

 d <- d[ complete.cases(d$days_to_event,d$black,d$adopt) , ]

dat <- list(
    days_to_event = as.integer( d$days_to_event ),
    color_id = as.integer( d$black ) ,
    adopted = as.integer( d$adopt )
)

m11.14 <- ulam(
    alist(
        days_to_event|adopted==1 ~ exponential( lambda ),
        days_to_event|adopted==0 ~ custom(exponential_lccdf( !Y | lambda )),
        lambda <- 1.0/mu,
        log(mu) <- a[color_id],
        a[color_id] ~ normal(0,1)
    ), data=dat , chains=4, cores=4 ) 

```
**ERROR message when I run the above code block:**

> [[1]]
> Stan model '7bd21d9b79bf04ab589340ced5533e09' does not contain samples.
> 
> [[2]]
> Stan model '7bd21d9b79bf04ab589340ced5533e09' does not contain samples.
> 
> [[3]]
> Stan model '7bd21d9b79bf04ab589340ced5533e09' does not contain samples.
> 
> [[4]]
> Stan model '7bd21d9b79bf04ab589340ced5533e09' does not contain samples.
> 
> Stan model '7bd21d9b79bf04ab589340ced5533e09' does not contain samples.
> Error in validObject(.Object): invalid class "ulam" object: invalid object for slot "coef" in class "ulam": got class "NULL", should be or extend class "numeric"
> Traceback:
> 
> 1. ulam(alist(days_to_event | adopted == 1 ~ exponential(lambda), 
>  .     days_to_event | adopted == 0 ~ custom(exponential_lccdf(!Y | 
>  .         lambda)), lambda <- 1/mu, log(mu) <- a[color_id], a[color_id] ~ 
>  .         normal(0, 1)), data = dat, chains = 4, cores = 4)
> 2. new("ulam", call = match.call(), model = model_code, stanfit = stanfit, 
>  .     coef = coef, vcov = varcov, data = data, start = list(start), 
>  .     pars = use_pars, formula = flist.orig, formula_parsed = formula_parsed)
> 3. initialize(value, ...)
> 4. initialize(value, ...)
> 5. validObject(.Object)
> 6. stop(msg, ": ", errors, domain = NA)

**Comment by rmcelreath** [comment]
Maybe you need to update rethinking. In any event, those error messages are not informative. You might need to use chains=1 to get informative error messages.

Feb 3 is the latest version of the text that is online.

**Comment by bingson** [comment]
```
m11.14 <- ulam(
    alist(
        days_to_event|adopted==1 ~ exponential( lambda ),
        days_to_event|adopted==0 ~ custom(exponential_lccdf( !Y | lambda )),
        lambda <- 1.0/mu,
        log(mu) <- a[color_id],
        a[color_id] ~ normal(0,1)
    ), data=dat , chains=1, cores=1 )
```
**Error message when chains=1**

> SAMPLING FOR MODEL '7bd21d9b79bf04ab589340ced5533e09' NOW (CHAIN 1).
> Chain 1: Unrecoverable error evaluating the log probability at the initial value.
> Chain 1: Exception: []: accessing element out of range. index 0 out of range; expecting index to be between 1 and 2; index position = 1a  (in 'model296c36153e74_7bd21d9b79bf04ab589340ced5533e09' at line 14)
> 
> [1] "Error in sampler$call_sampler(args_list[[i]]) : "                                                                                                                                                       
> [2] "  Exception: []: accessing element out of range. index 0 out of range; expecting index to be between 1 and 2; index position = 1a  (in 'model296c36153e74_7bd21d9b79bf04ab589340ced5533e09' at line 14)"
> [1] "error occurred during calling the sampler; sampling not done"
> Stan model '7bd21d9b79bf04ab589340ced5533e09' does not contain samples.
> Error in validObject(.Object): invalid class "ulam" object: invalid object for slot "coef" in class "ulam": got class "NULL", should be or extend class "numeric"
> Traceback:
> 
> 1. ulam(alist(days_to_event | adopted == 1 ~ exponential(lambda), 
>  .     days_to_event | adopted == 0 ~ custom(exponential_lccdf(!Y | 
>  .         lambda)), lambda <- 1/mu, log(mu) <- a[color_id], a[color_id] ~ 
>  .         normal(0, 1)), data = dat, chains = 1, cores = 1)
> 2. new("ulam", call = match.call(), model = model_code, stanfit = stanfit, 
>  .     coef = coef, vcov = varcov, data = data, start = list(start), 
>  .     pars = use_pars, formula = flist.orig, formula_parsed = formula_parsed)
> 3. initialize(value, ...)
> 4. initialize(value, ...)
> 5. validObject(.Object)
> 6. stop(msg, ": ", errors, domain = NA)

I also double-checked columns black, adopt, and days_to_event to make sure there were no weird entries.

**Comment by bingson** [comment]
I realize now that I was missing the `1L` integer assignment. Without that I would get the above error. 

```
d$adopt <- ifelse( d$out_event=="Adoption" , 1L , 0L )
dat <- list(
    days_to_event = as.numeric( d$days_to_event ),
    color_id = ifelse( d$color=="Black" , 1L , 2L ) ,
    adopted = d$adopt
)
```
