### ISSUE TITLE
Chapter 11 differences between m00 vs m11.14 

### ISSUE THREAD

**Issue by bingson** [rmcelreath/statrethinking_winter2019#9]
The Overthinking box still references `stancode(m00)` that doesn't exist in the Feb 14th 2019 version of Chp 11 (p. 368) with the key difference below.

**m00** (Jan 20th 2019 version)
```
log(lambda) <- a + b*black,
a ~ normal(0,1),
b ~ normal(0,1)
```
to **m11.14** (Feb 14th 2019 version)
```
lambda <- 1.0/mu,
log(mu) <- a[color_id],
a[color_id] ~ normal(0,1)
```

I think I understand the extract.samples code block for **m11.14**, but for **m00** how does one interpret the output of. 
```
post <- extract.samples( m00 ) 
post$D <- exp(post$a)
precis( post , 2 )
```

**Comment by balkinishu** [comment]
Is it possible to get the code for the censored cat adoption example visualizations on Slide 51 and 53 of Lecture 12. 

I am still trying to grok through the material on survival models in Chapter 11, but it seems like there are some missing sections in the text related to the above two graphs that are making that harder.
